# Config file for automatic testing at travis-ci.org

language: python

python:
  - 3.8
  - 3.7
  - 3.6
  - 3.5
  - 2.7
  - pypy
  - pypy3

# command to install dependencies: 
install: pip install mock

# command to run tests: 
script: python setup.py test

